export const weatherCodes = {
  0: { emoji: "☀️", description: "Céu Limpo" },
  1: { emoji: "🌤️", description: "Principalmente Limpo" },
  2: { emoji: "⛅", description: "Parcialmente Nublado" },
  3: { emoji: "☁️", description: "Nublado" },
  45: { emoji: "🌫️", description: "Névoa" },
  48: { emoji: "🌫️", description: "Névoa Congelante" },
  51: { emoji: "🌧️", description: "Chuvisco Leve" },
  53: { emoji: "🌧️", description: "Chuvisco Moderado" },
  55: { emoji: "🌧️", description: "Chuvisco Intenso" },
  56: { emoji: "🌨️", description: "Chuvisco Congelante Leve" },
  57: { emoji: "🌨️", description: "Chuvisco Congelante Intenso" },
  61: { emoji: "🌧️", description: "Chuva Leve" },
  63: { emoji: "🌧️", description: "Chuva Moderada" },
  65: { emoji: "⛈️", description: "Chuva Forte" },
  66: { emoji: "🌨️", description: "Chuva Congelante Leve" },
  67: { emoji: "🌨️", description: "Chuva Congelante Forte" },
  71: { emoji: "❄️", description: "Queda de Neve Leve" },
  73: { emoji: "❄️", description: "Queda de Neve Moderada" },
  75: { emoji: "❄️", description: "Queda de Neve Forte" },
  77: { emoji: "🌨️", description: "Grãos de Neve" },
  80: { emoji: "⛈️", description: "Pancadas de Chuva Leves" },
  81: { emoji: "⛈️", description: "Pancadas de Chuva Moderadas" },
  82: { emoji: "⛈️", description: "Pancadas de Chuva Violentas" },
  85: { emoji: "🌨️", description: "Pancadas de Neve Leves" },
  86: { emoji: "🌨️", description: "Pancadas de Neve Fortes" },
  95: { emoji: "⚡⛈️", description: "Trovoada" },
  96: { emoji: "⚡⛈️", description: "Trovoada com Granizo Leve" },
  99: { emoji: "⚡⛈️", description: "Trovoada com Granizo Forte" },
};
